# Generated by Django 4.2.5 on 2023-09-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=250, unique=True)),
                ("observacoes", models.TextField()),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=250, unique=True)),
                ("agencia", models.CharField(max_length=250)),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="banco.cliente"
                    ),
                ),
            ],
        ),
    ]
