# Generated by Django 4.2.5 on 2023-09-08 21:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="saldo",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
