# Generated by Django 4.2.5 on 2023-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banco", "0002_alter_conta_saldo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="saldo",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
