# Generated by Django 4.2.5 on 2023-09-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banco", "0004_alter_conta_saldo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="conta",
            name="agencia",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="conta",
            name="numero",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="conta",
            name="saldo",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
